import{test} from '@playwright/test'
import { CustomerPage } from '../../Pages/CustomerPage'
import { PersonalAccountPage} from '../../Pages/PersonalAccountPage'
import { AddressPage} from '../../Pages/AddressPage'
import { PhoneNumberPage} from '../../Pages/PhoneNumberPage'
import { EmailPage} from '../../Pages/EmailPage'
import { DealerAccountPage} from '../../Pages/DealerAccountPage'
import { DealerPhoneNumberPage} from '../../Pages/DealerPhoneNumberPage'

test('Creating regular account Print Bidder Aggreement with dealer',async({page}) =>  
{
    const customerpage = new CustomerPage(page)
    const personalaccountpage = new PersonalAccountPage(page) 
    const addresspage = new AddressPage(page)
    const phonenumberpage = new PhoneNumberPage(page)
    const emailpage = new EmailPage(page)
    const dealeraccountpage = new DealerAccountPage(page) 
    const dealerphonenumberpage = new DealerPhoneNumberPage(page)

    await customerpage.url()
    await customerpage.manager()
    await customerpage.customer()
    await personalaccountpage.accounttype_dropdown()
    await personalaccountpage.names()
    await personalaccountpage.save()
    await addresspage.newaddress()
    await addresspage.generaladdress()
    await addresspage.saveandclose()
    await phonenumberpage.phonenumberbtn()
    await phonenumberpage.General_PhoneNumber()
    await emailpage.NewEmailbtn()
    await emailpage.enter_emailid()
    await dealeraccountpage.accounttype_dropdown()
    await dealeraccountpage.names()
    await dealeraccountpage.save()
    await addresspage.newaddress()
    await addresspage.generaladdress()
    await addresspage.saveandclose()
    await dealerphonenumberpage.phonenumberbtn()
    await phonenumberpage.General_PhoneNumber()
    await dealeraccountpage.RelatedAccount()
    await personalaccountpage.RegularAccount_Print_Bidder_Aggreement()
})
test('Creating VIP account for  Personal and Dealer or Business Print Bidder Aggreement',async({page}) =>
{
    const customerpage = new CustomerPage(page)
    const personalaccountpage = new PersonalAccountPage(page) 
    const addresspage = new AddressPage(page)
    const phonenumberpage = new PhoneNumberPage(page)
    const emailpage = new EmailPage(page)
    const dealeraccountpage = new DealerAccountPage(page) 
    const dealerphonenumberpage = new DealerPhoneNumberPage(page)

    await customerpage.url()
    await customerpage.manager()
    await customerpage.customer()
    await personalaccountpage.accounttype_dropdown()
    await personalaccountpage.names()
    await personalaccountpage.save()
    await addresspage.newaddress()
    await addresspage.generaladdress()
    await addresspage.saveandclose()
    await phonenumberpage.phonenumberbtn()
    await phonenumberpage.General_PhoneNumber()
    await emailpage.NewEmailbtn()
    await emailpage.enter_emailid()
    await dealeraccountpage.accounttype_dropdown()
    await dealeraccountpage.names()
    await dealeraccountpage.save()
    await addresspage.newaddress()
    await addresspage.generaladdress()
    await addresspage.saveandclose()
    await dealerphonenumberpage.phonenumberbtn()
    await phonenumberpage.General_PhoneNumber()
    await dealeraccountpage.RelatedAccount()
    await personalaccountpage.VIP_Print_Bidder_Aggreement()
})
test('Creating Automobilia account for  Personal and Dealer or Business Print Bidder Aggreement',async({page}) =>
{
    const customerpage = new CustomerPage(page)
    const personalaccountpage = new PersonalAccountPage(page) 
    const addresspage = new AddressPage(page)
    const phonenumberpage = new PhoneNumberPage(page)
    const emailpage = new EmailPage(page)
    const dealeraccountpage = new DealerAccountPage(page) 
    const dealerphonenumberpage = new DealerPhoneNumberPage(page)

    await customerpage.url()
    await customerpage.manager()
    await customerpage.customer()
    await personalaccountpage.accounttype_dropdown()
    await personalaccountpage.names()
    await personalaccountpage.save()
    await addresspage.newaddress()
    await addresspage.generaladdress()
    await addresspage.saveandclose()
    await phonenumberpage.phonenumberbtn()
    await phonenumberpage.General_PhoneNumber()
    await emailpage.NewEmailbtn()
    await emailpage.enter_emailid()
    await dealeraccountpage.accounttype_dropdown()
    await dealeraccountpage.names()
    await dealeraccountpage.save()
    await addresspage.newaddress()
    await addresspage.generaladdress()
    await addresspage.saveandclose()
    await dealerphonenumberpage.phonenumberbtn()
    await phonenumberpage.General_PhoneNumber()
    await dealeraccountpage.RelatedAccount()
    await personalaccountpage.Automobilia_Print_Bidder_Aggreement()
})