import { expect } from '@playwright/test'
import { ConsignmentManager_WebElements } from '../WebElements/ConsignmentManager_WebElements'    
import { TestData } from '../TestData/testdata.js';

exports.ConsignmentManagerPage =
class ConsignmentManagerPage
{
    constructor(page)
    {
        this.page = page
        this.consignmentManager_webElements =  new ConsignmentManager_WebElements()
        this.testdata = new TestData()
    }
    async ChangeArea()
    {
       await this.page.locator(this.consignmentManager_webElements.Change_Area).click()
       await this.page.locator(this.consignmentManager_webElements.Consignment_Manger_Button).click()
       await this.page.locator(this.consignmentManager_webElements.Select_Consignment).click()
       
    }
    async Collections()
    {
       await this.page.locator(this.consignmentManager_webElements.Select_Collection_Option).click()
       await this.page.locator(this.consignmentManager_webElements.New_Collection_Button).click()
       await this.page.locator(this.consignmentManager_webElements.Name_Field).fill(this.testdata.Collection_Name)
       await this.page.waitForTimeout(500)
       await this.page.locator(this.consignmentManager_webElements.Description_Field).fill(this.testdata.Colection_Description)
       await this.page.waitForTimeout(2000)
       await this.page.locator(this.consignmentManager_webElements.SaveandClose).click()
       await this.page.locator(this.consignmentManager_webElements.CreatedOn_Filter).click()
       await this.page.locator(this.consignmentManager_webElements.NewtoOld).click()
       await this.page.waitForTimeout(2000)
    }
    async Charities()
    {
       await this.page.locator(this.consignmentManager_webElements.Select_Charities).click()
       await this.page.locator(this.consignmentManager_webElements.New_Charities_Button).click()
       await this.page.locator(this.consignmentManager_webElements.Name_Field).fill(this.testdata.Charities_Name)
        await this.page.waitForTimeout(500)
       await this.page.locator(this.consignmentManager_webElements.Description_Field).fill(this.testdata.Charities_Description)
       await this.page.waitForTimeout(500)
       await this.page.locator(this.consignmentManager_webElements.URL_Field).click()
       await this.page.locator(this.consignmentManager_webElements.URL_Field).fill(this.testdata.Charities_URL)
       await this.page.waitForTimeout(2000)
       await this.page.locator(this.consignmentManager_webElements.SaveandClose).click()
       await this.page.locator(this.consignmentManager_webElements.CreatedOn_Filter).click()
       await this.page.locator(this.consignmentManager_webElements.NewtoOld).click()
       await this.page.waitForTimeout(2000)
    }
    async Events()
    {
       await this.page.locator(this.consignmentManager_webElements.Select_Events).click()
       await this.page.locator(this.consignmentManager_webElements.Search_EventName).fill(this.testdata.Event_name)
       await this.page.waitForTimeout(1000)
       await this.page.keyboard.press('Enter')
       await this.page.waitForTimeout(2000)
       await this.page.locator(this.consignmentManager_webElements.Select_Particular_Event).dblclick()
       await this.page.locator(this.consignmentManager_webElements.Select_Consignment_Event).click()
       await this.page.locator(this.consignmentManager_webElements.Collection_Add_Existing_Button).click()
       await this.page.locator(this.consignmentManager_webElements.CreatedOn_Filter_Event).click()
       await this.page.locator(this.consignmentManager_webElements.NewtoOld).click()
       await this.page.waitForTimeout(2000)
       await this.page.locator(this.consignmentManager_webElements.Select_Created_Collection).click()
       await this.page.locator(this.consignmentManager_webElements.SaveandClose_PopUp).click()
       await this.page.waitForTimeout(4000)

       await this.page.locator(this.consignmentManager_webElements.Charity_Add_Existing_Button).click()
       await this.page.locator(this.consignmentManager_webElements.CreatedOn_Filter_Event).click()
       await this.page.waitForTimeout(1000)
       await this.page.locator(this.consignmentManager_webElements.NewtoOld).click()
       await this.page.waitForTimeout(2000)
       await this.page.locator(this.consignmentManager_webElements.Select_Created_Charity).click()
       await this.page.locator(this.consignmentManager_webElements.SaveandClose_PopUp).click()
       await this.page.waitForTimeout(4000)
    }
    async Dockets()
    {
      await this.page.waitForTimeout(4000)
      await this.page.locator(this.consignmentManager_webElements.Docket).click()
      const frame = await this.page.frameLocator(this.consignmentManager_webElements.iframe_DocketLaunch)
                    if(!frame) throw new Error('Iframe not found')
      await frame.locator(this.consignmentManager_webElements.SelectEvent).selectOption(this.testdata.Event_nameSD2025)
      await this.page.waitForTimeout(3000)
      await frame.locator(this.consignmentManager_webElements.SelectDays).selectOption({ index: 0 })
      await this.page.waitForTimeout(1000)
      await frame.locator(this.consignmentManager_webElements.LaunchButton).click()
      await this.page.waitForTimeout(5000)
      const frame1 = await this.page.frameLocator(this.consignmentManager_webElements.Iframe_DaysOfConsign)
                    if(!frame1) throw new Error('Iframe not found')
      await frame1.locator(this.consignmentManager_webElements.Day1Prime).click()
      await this.page.waitForTimeout(4000)
      await frame1.locator(this.consignmentManager_webElements.Day1Pm).click()
      await this.page.waitForTimeout(4000)
      await frame1.locator(this.consignmentManager_webElements.Other).click()
      await this.page.waitForTimeout(4000)
      await frame1.locator(this.consignmentManager_webElements.Seach_Field).fill(this.testdata.FirstName)
      await frame1.locator(this.consignmentManager_webElements.FirstCIdCheckbox).click()
      await this.page.waitForTimeout(1000)
      await frame1.locator(this.consignmentManager_webElements.FirstAssign_Button).click()
      await this.page.waitForTimeout(1000)
      await frame1.locator(this.consignmentManager_webElements.SelectAssign).click()
      const frame2 = await this.page.frameLocator(this.consignmentManager_webElements.iframeAssignLot)
                    if(!frame2) throw new Error('Iframe not found')
                await this.page.waitForTimeout(5000)     
      await frame2.locator(this.consignmentManager_webElements.AutoAssign).click()
      await this.page.waitForTimeout(2000)  
      await frame2.locator(this.consignmentManager_webElements.SaveAutoAssign_Button).click()
      await this.page.waitForTimeout(6000) 
      await this.page.locator(this.consignmentManager_webElements.Close_AutoAssign).click()
      await this.page.waitForTimeout(6000)
      await frame1.locator(this.consignmentManager_webElements.Time_Button).click()
      await this.page.waitForTimeout(3000)
      await frame1.locator(this.consignmentManager_webElements.Cancelled_Button).click()
      await this.page.waitForTimeout(3000)
      await frame1.locator(this.consignmentManager_webElements.SlideShow_Button).click()
      await this.page.waitForTimeout(5000)
      await this.page.locator(this.consignmentManager_webElements.Close_SlideShow).click()
      await this.page.waitForTimeout(3000)
       const [newPage] = await Promise.all
             ([
                this.page.context().waitForEvent('page'),
                await frame1.locator(this.consignmentManager_webElements.Trend_Button).click()
            ]);
      await newPage.waitForLoadState('load');
      await this.page.waitForTimeout(60000)
      await newPage.close();
      await frame1.locator(this.consignmentManager_webElements.Refresh_Button).click()
      await this.page.waitForTimeout(3000)
      await this.page.locator(this.consignmentManager_webElements.Close_Docket).click()
      await this.page.waitForTimeout(5000)
    }
    async Consignment()
    {
       await this.page.locator(this.consignmentManager_webElements.Select_Consignments_Option).click()
       await this.page.waitForTimeout(2000)
       await this.page.locator(this.consignmentManager_webElements.Open_Consignment).dblclick()
       await this.page.waitForTimeout(2000)
       await this.page.locator(this.consignmentManager_webElements.On_Charity_Toggle).click()
       await this.page.locator(this.consignmentManager_webElements.Save_Button).click()
       await this.page.waitForTimeout(2000)
       await this.page.locator(this.consignmentManager_webElements.Add_Buyer).click()
       await this.page.locator(this.consignmentManager_webElements.Customer_Field).fill(this.testdata.Account_Name)
       await this.page.waitForTimeout(2000)
       await this.page.locator(this.consignmentManager_webElements.Select_Account).click()
       await this.page.locator(this.consignmentManager_webElements.HammerAmount_Field).click()
       await this.page.locator(this.consignmentManager_webElements.HammerAmount_Field).fill(this.testdata.Hammer_Amount)
       await this.page.locator(this.consignmentManager_webElements.SaveandClose_ConsignmentContact).click()
       await this.page.waitForTimeout(3000)
       await this.page.locator(this.consignmentManager_webElements.Add_Donor).click()
       await this.page.locator(this.consignmentManager_webElements.Customer_Field).fill(this.testdata.Account_Name)
       await this.page.waitForTimeout(2000)
       await this.page.locator(this.consignmentManager_webElements.Select_Account).click()
       await this.page.waitForTimeout(500)
       await this.page.locator(this.consignmentManager_webElements.DonationAmount_Field).click()
       await this.page.locator(this.consignmentManager_webElements.DonationAmount_Field).fill(this.testdata.Donation_Amount)
       await this.page.locator(this.consignmentManager_webElements.SaveandClose_ConsignmentContact).click()
       await this.page.screenshot({ path: './ScreenShot/BuyerDonarPrice.png', fullPage: true})
       await this.page.waitForTimeout(3000)
    }
    async MarkettingTab()
    {
       await this.page.locator(this.consignmentManager_webElements.Marketting_Tab).click()
       await this.page.locator(this.consignmentManager_webElements.Add_Collection).click()
       await this.page.waitForTimeout(2000)
       await this.page.locator(this.consignmentManager_webElements.CreatedOn).click()
       await this.page.waitForTimeout(2000)
       await this.page.locator(this.consignmentManager_webElements.NewtoOld).click()
       await this.page.waitForTimeout(2000)
      //  await this.page.locator(this.consignmentManager_webElements.HoverFirstRow).hover()
      //  await this.page.locator(this.consignmentManager_webElements.Select_FirstRow).click()
        await this.page.getByLabel('Event Collection', { exact: true }).locator('div').filter({ hasText: /^Toggle selection of all rows$/ }).nth(1).click()
        await this.page.waitForTimeout(1000)
      //  await this.page.locator(this.consignmentManager_webElements.Select_Collection).click()
        await this.page.locator(this.consignmentManager_webElements.SaveandClose_Collection).click()
        await this.page.waitForTimeout(4000)
        await this.page.screenshot({ path: './ScreenShot/Collections.png', fullPage: true})
         // await this.page.locator(this.consignmentManager_webElements.DoubleClick_Collection).dblclick()
         // await this.page.waitForTimeout(4000)
         // await this.page.screenshot({ path: './ScreenShot/CollectionsInside.png', fullPage: true})
         //await this.page.locator(this.consignmentManager_webElements.GoBack_Button).click()
         await this.page.waitForTimeout(2000)

        await this.page.locator(this.consignmentManager_webElements.Add_Charities).click()
       await this.page.waitForTimeout(2000)
       await this.page.locator(this.consignmentManager_webElements.CreatedOnCharity).click()
       await this.page.waitForTimeout(2000)
       await this.page.locator(this.consignmentManager_webElements.NewtoOld).click()
       await this.page.waitForTimeout(2000)
      //  await this.page.locator(this.consignmentManager_webElements.HoverFirstRow).hover()
      //  await this.page.locator(this.consignmentManager_webElements.Select_FirstRow).click()
        await this.page.getByLabel('EventCharityAssociationSubgrid').locator('div').filter({ hasText: /^Toggle selection of all rows$/ }).nth(1).click()
        await this.page.waitForTimeout(1000)
        //await this.page.locator(this.consignmentManager_webElements.Select_Charity_Association).click()
        await this.page.locator(this.consignmentManager_webElements.SaveandClose_Collection).click()
        await this.page.waitForTimeout(4000)
        await this.page.screenshot({ path: './ScreenShot/Chariry.png', fullPage: true})
      //   await this.page.locator(this.consignmentManager_webElements.DoubleClick_Charities).dblclick()
      //   await this.page.waitForTimeout(4000)
      //   await this.page.screenshot({ path: './ScreenShot/ChariryInside.png', fullPage: true})
       // await this.page.locator(this.consignmentManager_webElements.GoBack_Button).click()
        await this.page.waitForTimeout(2000)
    }

    async BidderManager()
    {
      await this.page.locator(this.consignmentManager_webElements.Change_Area).click()
       await this.page.locator(this.consignmentManager_webElements.Bidder_Manger_Button).click()
       await this.page.locator(this.consignmentManager_webElements.Select_PackageTracking).click()
       await this.page.waitForTimeout(2000)
       await this.page.locator(this.consignmentManager_webElements.Select_Bulk_PackageTracking).click()

        const frame = await this.page.frameLocator(this.consignmentManager_webElements.Iframe_Bulk_PackageTracking)
                    if(!frame) throw new Error('Iframe not found')
                    await this.page.waitForTimeout(2000)
                    await frame.locator(this.consignmentManager_webElements.Select_Event).click()
                    await this.page.locator(this.consignmentManager_webElements.Enter_EventName).click()
                    await this.page.locator(this.consignmentManager_webElements.Enter_EventName).fill(this.testdata.Event_Name)
                    await this.page.waitForTimeout(2000)
                    await this.page.locator(this.consignmentManager_webElements.Select_CurrentEvent).click()
                    await this.page.waitForTimeout(1000)
                    await this.page.locator(this.consignmentManager_webElements.Add_Button).click()
                    await this.page.waitForTimeout(3000)

                    await frame.locator(this.consignmentManager_webElements.Select_Search_Type_Options).selectOption(this.testdata.Bidder_Number_by_Range)
                    await frame.locator(this.consignmentManager_webElements.Bidder_Start).click()
                    await frame.locator(this.consignmentManager_webElements.Bidder_Start).fill(this.testdata.Lot_starting)
                    await frame.locator(this.consignmentManager_webElements.Bidder_End).click()
                    await frame.locator(this.consignmentManager_webElements.Bidder_End).fill(this.testdata.Lot_Ending)
                    await frame.locator(this.consignmentManager_webElements.SearchButton).click()
                    await frame.locator(this.consignmentManager_webElements.Change_Tracking_Number).click()
                    await this.page.waitForTimeout(1000)
                    await frame.locator(this.consignmentManager_webElements.Change_Tracking_Number).fill(this.testdata.Tracking_Number)
                    await frame.locator(this.consignmentManager_webElements.SaveAll_Button).click()
                    await this.page.locator(this.consignmentManager_webElements.Ok_Button).click()
                    await this.page.waitForTimeout(5000)
                    await this.page.screenshot({ path: './ScreenShot/BulkBidderManagerPageTrackingNumber.png', fullPage: true})

                    await frame.locator(this.consignmentManager_webElements.Select_Search_Type_Options).selectOption(this.testdata.All_Bidders)
                    await frame.locator(this.consignmentManager_webElements.SearchButton).click()
                    await this.page.waitForTimeout(5000)
                    await this.page.screenshot({ path: './ScreenShot/BulkBidderManagerPageAllBidder.png', fullPage: true})

                    await frame.locator(this.consignmentManager_webElements.Select_Search_Type_Options).selectOption(this.testdata.All_Buyers)
                    await frame.locator(this.consignmentManager_webElements.SearchButton).click()
                    await this.page.waitForTimeout(5000)
                    await this.page.screenshot({ path: './ScreenShot/BulkBidderManagerPageAllBuyer.png', fullPage: true})

                    await frame.locator(this.consignmentManager_webElements.Select_Search_Type_Options).selectOption(this.testdata.Buyser_ByLot)
                    await frame.locator(this.consignmentManager_webElements.Search_Lot_Field).click()
                    await frame.locator(this.consignmentManager_webElements.Search_Lot_Field).fill(this.testdata.BuyerLot)
                    await frame.locator(this.consignmentManager_webElements.SearchButton).click()
                    await this.page.waitForTimeout(5000)
                    await this.page.screenshot({ path: './ScreenShot/BulkBidderManagerPageByLot.png', fullPage: true})

                    await frame.locator(this.consignmentManager_webElements.Select_Search_Type_Options).selectOption(this.testdata.Buyser_ByCancel)
                    await frame.locator(this.consignmentManager_webElements.Search_Lot_Field).click()
                    await frame.locator(this.consignmentManager_webElements.Search_Lot_Field).fill(this.testdata.BuyerCancel)
                    await frame.locator(this.consignmentManager_webElements.SearchButton).click()
                    await this.page.waitForTimeout(5000)
                    await this.page.screenshot({ path: './ScreenShot/BulkBidderManagerPageCancel.png', fullPage: true})

    }
}