import { expect } from '@playwright/test'
import { SeatReservation_WebElements } from '../WebElements/SeatReservation_WebElements.js'    
import { TestData } from '../TestData/testdata.js';

exports.SeatReservationPage =
class SeatReservationPage
{
    constructor(page)
    {
        this.page = page
        this.seatreservation_webelements =  new SeatReservation_WebElements()
        this.testdata = new TestData()
    }


    async ChangeArea_Adminstartion()
    {
        await this.page.locator(this.seatreservation_webelements.Change_Area).click()
        await this.page.locator(this.seatreservation_webelements.Administartion_Button).click()
    }
    async Auction_Seating()
    {
        await this.page.locator(this.seatreservation_webelements.Auction_Seating).click()
    }
    async Seat_Defination()
    {
        await this.page.locator(this.seatreservation_webelements.Seat_Defination).click()
        await this.page.waitForTimeout(10000)
        await this.page.screenshot({ path: './ScreenShot/159 seat Defination.png', fullPage: true})
    }
    async View_Reservation_Arena()
    {
        await this.page.locator(this.seatreservation_webelements.View_Reservation).click()
        await this.page.waitForTimeout(5000)
        await this.page.screenshot({ path: './ScreenShot/160 View_Reservation.png', fullPage: true})
        const frame1 = await this.page.frameLocator(this.seatreservation_webelements.iframe_SeatReservation)
        if(!frame1) throw new Error('Iframe not found')
        await frame1.locator(this.seatreservation_webelements.SelectSeat_Defination_Dropdown).selectOption({ index: 1 })
        await this.page.waitForTimeout(2000)
        await frame1.locator(this.seatreservation_webelements.Launch_Button).click()
        await this.page.waitForTimeout(5000)
        const frame = await this.page.frameLocator(this.seatreservation_webelements.Iframe_SeatChart)
        if(!frame) throw new Error('Iframe not found')
        await frame.locator(this.seatreservation_webelements.Seat_52).click()
        await frame.locator(this.seatreservation_webelements.Seat_53).click()
        await frame.locator(this.seatreservation_webelements.Seat_54).click()
        await this.page.waitForTimeout(2000)
        await frame.locator(this.seatreservation_webelements.Block_Seat).click()
        await this.page.locator(this.seatreservation_webelements.Yes_BlockSeat).click()
        await this.page.locator(this.seatreservation_webelements.Ok_Button).click()
        await this.page.waitForTimeout(2000)
        await frame.locator(this.seatreservation_webelements.Seat_52).click()
        await frame.locator(this.seatreservation_webelements.Seat_53).click()
        await frame.locator(this.seatreservation_webelements.Seat_54).click()
        await this.page.waitForTimeout(1000)
        await frame.locator(this.seatreservation_webelements.UnBlock_Seat).click()
        await this.page.locator(this.seatreservation_webelements.Yes_UnBlockSeat).click()
        await this.page.locator(this.seatreservation_webelements.Ok_Button).click()
        await this.page.waitForTimeout(2000)
        await frame.locator(this.seatreservation_webelements.Seat_52).click()
        await frame.locator(this.seatreservation_webelements.Seat_53).click()
        await frame.locator(this.seatreservation_webelements.Seat_54).click()
        await frame.locator(this.seatreservation_webelements.Reserve_Seat).click()
        await this.page.waitForTimeout(4000)
        await frame.locator(this.seatreservation_webelements.Clear_Seat).click()
        await this.page.waitForTimeout(2000)
        await frame.locator(this.seatreservation_webelements.Cancel_Button).click()
        await this.page.waitForTimeout(2000)
        await frame.locator(this.seatreservation_webelements.Seat_52).click()
        await frame.locator(this.seatreservation_webelements.Seat_53).click()
        await frame.locator(this.seatreservation_webelements.Seat_54).click()
        await frame.locator(this.seatreservation_webelements.Reserve_Seat).click()
        await this.page.waitForTimeout(4000)
        await frame.locator(this.seatreservation_webelements.Search_Button).click()
        await this.page.waitForTimeout(2000)
        await this.page.screenshot({ path: './ScreenShot/161 Reserve seat in Arena.png', fullPage: true})
        await this.page.locator(this.seatreservation_webelements.Search_Account).click()
        await this.page.locator(this.seatreservation_webelements.Search_Account).fill(this.testdata.Collection_Name)
        await this.page.locator(this.seatreservation_webelements.First_Account).click()
        await this.page.waitForTimeout(2000)
        await this.page.locator(this.seatreservation_webelements.Add_Account).click()
        await this.page.waitForTimeout(2000)
        await frame.locator(this.seatreservation_webelements.Reserve_Seat_Popup).click()
        await this.page.locator(this.seatreservation_webelements.Ok_Button).click()
        //await frame.locator(this.seatreservation_webelements.Open_Reserved_Seat).click()

        const [newPage] = await Promise.all([
                        this.page.context().waitForEvent('page'),
                        frame.locator(this.seatreservation_webelements.Open_Reserved_Seat).click()
                    ]);
        await this.page.waitForTimeout(4000)            
        await newPage.locator(this.seatreservation_webelements.Reservation_Button).click()
        await this.page.waitForTimeout(4000)
        await newPage.locator(this.seatreservation_webelements.Open_Active_Reservation).dblclick()
        await this.page.waitForTimeout(8000)
        await newPage.close();
        await frame.locator(this.seatreservation_webelements.Seat_52).click()
        await frame.locator(this.seatreservation_webelements.Seat_53).click()
        await frame.locator(this.seatreservation_webelements.Seat_54).click()
        await frame.locator(this.seatreservation_webelements.Cancel_Seat).click()
        await this.page.locator(this.seatreservation_webelements.Yes_CancelSeat).click()
        await this.page.waitForTimeout(4000)
        await frame.locator(this.seatreservation_webelements.Seat_52).click()
        await this.page.screenshot({ path: './ScreenShot/162 Cancel Reserve seat in Arena.png', fullPage: true})
        await this.page.locator(this.seatreservation_webelements.Close_SeatChart).click()
        await this.page.waitForTimeout(2000)
    }
     async View_Reservation_HammerHigh4()
    {
        const frame1 = await this.page.frameLocator(this.seatreservation_webelements.iframe_SeatReservation)
        if(!frame1) throw new Error('Iframe not found')
        await frame1.locator(this.seatreservation_webelements.SelectSeat_Defination_Dropdown).selectOption({ index: 2 })
        await this.page.waitForTimeout(2000)
        await frame1.locator(this.seatreservation_webelements.Launch_Button).click()
        await this.page.waitForTimeout(5000)
        const frame = await this.page.frameLocator(this.seatreservation_webelements.Iframe_SeatChart)
        if(!frame) throw new Error('Iframe not found')
        await frame.locator(this.seatreservation_webelements.Select_E_Table).click()
        await this.page.waitForTimeout(2000)
        await frame.locator(this.seatreservation_webelements.ClearAll_E_Table).click()
        await this.page.waitForTimeout(2000)
        await frame.locator(this.seatreservation_webelements.Select_E_Table).click()
        await this.page.waitForTimeout(2000)
         await frame.locator(this.seatreservation_webelements.Block_Seat).click()
        await this.page.locator(this.seatreservation_webelements.Yes_BlockSeat).click()
        await this.page.locator(this.seatreservation_webelements.Ok_Button).click()
        await this.page.waitForTimeout(2000)
        await frame.locator(this.seatreservation_webelements.Select_E_Table).click()
        await this.page.waitForTimeout(1000)
        await frame.locator(this.seatreservation_webelements.UnBlock_Seat).click()
        await this.page.locator(this.seatreservation_webelements.Yes_UnBlockSeat).click()
        await this.page.locator(this.seatreservation_webelements.Ok_Button).click()
        await this.page.waitForTimeout(2000)
        await frame.locator(this.seatreservation_webelements.Select_E_Table).click()
        await frame.locator(this.seatreservation_webelements.Reserve_Seat).click()
        await this.page.waitForTimeout(4000)
        await frame.locator(this.seatreservation_webelements.Clear_Seat).click()
        await this.page.waitForTimeout(2000)
        await frame.locator(this.seatreservation_webelements.Cancel_Button).click()
        await this.page.waitForTimeout(2000)
        await frame.locator(this.seatreservation_webelements.Select_E_Table).click()
        await frame.locator(this.seatreservation_webelements.Reserve_Seat).click()
        await this.page.waitForTimeout(4000)
        await frame.locator(this.seatreservation_webelements.Search_Button).click()
        await this.page.waitForTimeout(2000)
        await this.page.screenshot({ path: './ScreenShot/162.1 Reserve seat in High 4.png', fullPage: true})
        await this.page.locator(this.seatreservation_webelements.Search_Account).click()
        await this.page.locator(this.seatreservation_webelements.Search_Account).fill(this.testdata.Collection_Name)
        await this.page.locator(this.seatreservation_webelements.First_Account).click()
        await this.page.waitForTimeout(2000)
        await this.page.locator(this.seatreservation_webelements.Add_Account).click()
        await this.page.waitForTimeout(2000)
        await frame.locator(this.seatreservation_webelements.Reserve_Seat_Popup).click()
        await this.page.locator(this.seatreservation_webelements.Ok_Button).click()
        //await frame.locator(this.seatreservation_webelements.Open_Reserved_Seat).click()

        const [newPage] = await Promise.all([
                        this.page.context().waitForEvent('page'),
                        frame.locator(this.seatreservation_webelements.OpenResertved_Seat_High4).click()
                    ]);
        await this.page.waitForTimeout(4000)            
        await newPage.locator(this.seatreservation_webelements.Reservation_Button).click()
        await this.page.waitForTimeout(4000)
        await newPage.locator(this.seatreservation_webelements.Open_Active_Reservation).dblclick()
        await this.page.waitForTimeout(8000)
        await newPage.close();
        await frame.locator(this.seatreservation_webelements.Select_E_Table).click()
        await frame.locator(this.seatreservation_webelements.Cancel_Seat).click()
        await this.page.locator(this.seatreservation_webelements.Yes_CancelSeat).click()
        await this.page.waitForTimeout(4000)
        await frame.locator(this.seatreservation_webelements.Select_E_Table).click()
        await this.page.screenshot({ path: './ScreenShot/163 Cancel Reserve seat in High 4.png', fullPage: true})
        await this.page.locator(this.seatreservation_webelements.Close_SeatChart).click()
        await this.page.waitForTimeout(2000)
    }
         async View_Reservation_HammerHigh8()
    {
        const frame1 = await this.page.frameLocator(this.seatreservation_webelements.iframe_SeatReservation)
        if(!frame1) throw new Error('Iframe not found')
        await frame1.locator(this.seatreservation_webelements.SelectSeat_Defination_Dropdown).selectOption({ index: 3 })
        await this.page.waitForTimeout(2000)
        await frame1.locator(this.seatreservation_webelements.Launch_Button).click()
        await this.page.waitForTimeout(5000)
        const frame = await this.page.frameLocator(this.seatreservation_webelements.Iframe_SeatChart)
        if(!frame) throw new Error('Iframe not found')
        await frame.locator(this.seatreservation_webelements.Select_E_Table).click()
        await this.page.waitForTimeout(2000)
        await frame.locator(this.seatreservation_webelements.ClearAll_E_Table).click()
        await this.page.waitForTimeout(2000)
        await frame.locator(this.seatreservation_webelements.Select_E_Table).click()
        await this.page.waitForTimeout(2000)
         await frame.locator(this.seatreservation_webelements.Block_Seat).click()
        await this.page.locator(this.seatreservation_webelements.Yes_BlockSeat).click()
        await this.page.locator(this.seatreservation_webelements.Ok_Button).click()
        await this.page.waitForTimeout(2000)
        await frame.locator(this.seatreservation_webelements.Select_E_Table).click()
        await this.page.waitForTimeout(1000)
        await frame.locator(this.seatreservation_webelements.UnBlock_Seat).click()
        await this.page.locator(this.seatreservation_webelements.Yes_UnBlockSeat).click()
        await this.page.locator(this.seatreservation_webelements.Ok_Button).click()
        await this.page.waitForTimeout(2000)
        await frame.locator(this.seatreservation_webelements.Select_E_Table).click()
        await frame.locator(this.seatreservation_webelements.Reserve_Seat).click()
        await this.page.waitForTimeout(4000)
        await frame.locator(this.seatreservation_webelements.Clear_Seat).click()
        await this.page.waitForTimeout(2000)
        await frame.locator(this.seatreservation_webelements.Cancel_Button).click()
        await this.page.waitForTimeout(2000)
        await frame.locator(this.seatreservation_webelements.Select_E_Table).click()
        await frame.locator(this.seatreservation_webelements.Reserve_Seat).click()
        await this.page.waitForTimeout(4000)
        await frame.locator(this.seatreservation_webelements.Search_Button).click()
        await this.page.waitForTimeout(2000)
        await this.page.screenshot({ path: './ScreenShot/164  Reserve seat in High 8.png', fullPage: true})
        await this.page.locator(this.seatreservation_webelements.Search_Account).click()
        await this.page.locator(this.seatreservation_webelements.Search_Account).fill(this.testdata.Collection_Name)
        await this.page.locator(this.seatreservation_webelements.First_Account).click()
        await this.page.waitForTimeout(2000)
        await this.page.locator(this.seatreservation_webelements.Add_Account).click()
        await this.page.waitForTimeout(2000)
        await frame.locator(this.seatreservation_webelements.Reserve_Seat_Popup).click()
        await this.page.locator(this.seatreservation_webelements.Ok_Button).click()
        //await frame.locator(this.seatreservation_webelements.Open_Reserved_Seat).click()

        const [newPage] = await Promise.all([
                        this.page.context().waitForEvent('page'),
                        frame.locator(this.seatreservation_webelements.OpenResertved_Seat_High4).click()
                    ]);
        await this.page.waitForTimeout(4000)            
        await newPage.locator(this.seatreservation_webelements.Reservation_Button).click()
        await this.page.waitForTimeout(4000)
        await newPage.locator(this.seatreservation_webelements.Open_Active_Reservation).dblclick()
        await this.page.waitForTimeout(8000)
        await newPage.close();
        await frame.locator(this.seatreservation_webelements.Select_E_Table).click()
        await frame.locator(this.seatreservation_webelements.Cancel_Seat).click()
        await this.page.locator(this.seatreservation_webelements.Yes_CancelSeat).click()
        await this.page.waitForTimeout(4000)
        await frame.locator(this.seatreservation_webelements.Select_E_Table).click()
        await this.page.screenshot({ path: './ScreenShot/165 Cancel  Reserve seat in High 8.png', fullPage: true})
        await this.page.locator(this.seatreservation_webelements.Close_SeatChart).click()
        await this.page.waitForTimeout(2000)
    }
    async Seat_Reservation()
    {
        await this.page.locator(this.seatreservation_webelements.Seat_Reservation).click()
        await this.page.waitForTimeout(4000)
        const frame = await this.page.frameLocator(this.seatreservation_webelements.Iframe_SeatReservationView)
        if(!frame) throw new Error('Iframe not found')
        await frame.locator(this.seatreservation_webelements.Select_Event).selectOption({ index: 1 })
        await this.page.waitForTimeout(2000)
        await frame.locator(this.seatreservation_webelements.Select_SearchDefination).selectOption({ index: 1 })
        await this.page.waitForTimeout(2000)
        await frame.locator(this.seatreservation_webelements.Search_Filter).fill(this.testdata.Collection_Name)
        await this.page.screenshot({ path: './ScreenShot/166 View  Reserve seat in High 4.png', fullPage: true})
        await this.page.waitForTimeout(3000)
        await frame.locator(this.seatreservation_webelements.Search_Filter).clear()
        await this.page.waitForTimeout(2000)
        await frame.locator(this.seatreservation_webelements.Select_SearchDefination).selectOption({ index: 2 })
        await this.page.waitForTimeout(2000)
        await frame.locator(this.seatreservation_webelements.Search_Filter).fill(this.testdata.Collection_Name)
        await this.page.waitForTimeout(3000)
        await this.page.screenshot({ path: './ScreenShot/167 View  Reserve seat in High 8.png', fullPage: true})
        await frame.locator(this.seatreservation_webelements.Search_Filter).clear()
        await this.page.waitForTimeout(2000)
        await frame.locator(this.seatreservation_webelements.Select_SearchDefination).selectOption({ index: 3 })
        await this.page.waitForTimeout(2000)
        await frame.locator(this.seatreservation_webelements.Search_Filter).fill(this.testdata.Collection_Name)
        await this.page.waitForTimeout(3000)
        await this.page.screenshot({ path: './ScreenShot/168 View  Reserve seat in Arena.png', fullPage: true})
        await frame.locator(this.seatreservation_webelements.Search_Filter).clear()
        await this.page.waitForTimeout(2000)
    }
}